"""
pdf_report.py
--------------
Generates a downloadable PDF report for a single loan prediction using
ReportLab. The report includes applicant details, the prediction
result, approval probability, risk score, top contributing factors,
and the date/time of the prediction.
"""

import io
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT

PRIMARY_COLOR = colors.HexColor("#0B3D91")
SUCCESS_COLOR = colors.HexColor("#1FAA59")
DANGER_COLOR = colors.HexColor("#E0433B")
LIGHT_GREY = colors.HexColor("#F2F4F7")


def generate_pdf_report(record: dict) -> bytes:
    """
    Build a PDF report (as raw bytes) for the given prediction record.

    Parameters
    ----------
    record : dict
        A prediction record (as stored in the database), plus an optional
        "top_factors_list" key containing a list of explanation dicts.

    Returns
    -------
    bytes
        The generated PDF file content.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=20 * mm, bottomMargin=20 * mm,
        leftMargin=20 * mm, rightMargin=20 * mm,
        title="Loan Prediction Report",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], textColor=PRIMARY_COLOR, fontSize=20, spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "SubtitleStyle", parent=styles["Normal"], textColor=colors.grey, fontSize=10,
        alignment=TA_CENTER, spaceAfter=12,
    )
    section_style = ParagraphStyle(
        "SectionStyle", parent=styles["Heading2"], textColor=PRIMARY_COLOR, fontSize=13,
        spaceBefore=14, spaceAfter=6,
    )
    normal_style = ParagraphStyle(
        "NormalStyle", parent=styles["Normal"], fontSize=10, leading=15,
    )

    elements = []

    # ---- Header ----
    elements.append(Paragraph("Loan Approval Prediction Report", title_style))
    elements.append(Paragraph("Generated by the Loan Approval Prediction System", subtitle_style))
    elements.append(HRFlowable(width="100%", color=PRIMARY_COLOR, thickness=1.2))
    elements.append(Spacer(1, 10))

    # ---- Result banner ----
    is_approved = record.get("prediction") == "Approved"
    result_color = SUCCESS_COLOR if is_approved else DANGER_COLOR
    result_text = "LOAN APPROVED" if is_approved else "LOAN REJECTED"

    result_table = Table(
        [[Paragraph(f"<b><font color='white' size=14>{result_text}</font></b>", styles["Normal"])]],
        colWidths=[170 * mm],
    )
    result_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), result_color),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(result_table)
    elements.append(Spacer(1, 12))

    # ---- Prediction summary ----
    elements.append(Paragraph("Prediction Summary", section_style))
    probability = record.get("probability", 0)
    risk_score = record.get("risk_score", 0)
    summary_data = [
        ["Approval Probability", f"{probability:.2f}%"],
        ["Risk Score", f"{risk_score:.2f} / 100"],
        ["Model Used", record.get("model_used", "N/A")],
        ["Date & Time", record.get("created_at", datetime.now().strftime("%Y-%m-%d %H:%M:%S"))],
        ["Report ID", str(record.get("id", "N/A"))],
    ]
    summary_table = Table(summary_data, colWidths=[60 * mm, 110 * mm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), LIGHT_GREY),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D5DD")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(summary_table)

    # ---- Applicant details ----
    elements.append(Paragraph("Applicant Details", section_style))
    applicant_data = [
        ["Gender", record.get("gender", "N/A")],
        ["Marital Status", record.get("married", "N/A")],
        ["Dependents", record.get("dependents", "N/A")],
        ["Education", record.get("education", "N/A")],
        ["Self Employed", record.get("self_employed", "N/A")],
        ["Applicant Income", f"{record.get('applicant_income', 0):,.0f}"],
        ["Co-applicant Income", f"{record.get('coapplicant_income', 0):,.0f}"],
        ["Loan Amount (in thousands)", f"{record.get('loan_amount', 0):,.0f}"],
        ["Loan Term (months)", f"{record.get('loan_amount_term', 0):,.0f}"],
        ["Credit History", "Good" if record.get("credit_history", 0) == 1 else "No / Poor History"],
        ["Property Area", record.get("property_area", "N/A")],
    ]
    applicant_table = Table(applicant_data, colWidths=[60 * mm, 110 * mm])
    applicant_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), LIGHT_GREY),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D0D5DD")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(applicant_table)

    # ---- Explainable AI section ----
    top_factors = record.get("top_factors_list")
    if top_factors:
        elements.append(Paragraph("Top Factors Influencing This Decision", section_style))
        for i, factor in enumerate(top_factors, start=1):
            bullet_hex = "#1FAA59" if factor.get("direction") == "positive" else "#E0433B"
            text = (
                f"<b>{i}. {factor.get('label')}</b> "
                f"<font color='{bullet_hex}'>"
                f"({'+' if factor.get('direction') == 'positive' else '-'} impact)</font><br/>"
                f"{factor.get('explanation')}"
            )
            elements.append(Paragraph(text, normal_style))
            elements.append(Spacer(1, 4))

    elements.append(Spacer(1, 16))
    elements.append(HRFlowable(width="100%", color=colors.HexColor("#D0D5DD"), thickness=0.8))
    footer_style = ParagraphStyle(
        "FooterStyle", parent=styles["Normal"], fontSize=8, textColor=colors.grey,
        alignment=TA_CENTER, spaceBefore=8,
    )
    elements.append(Paragraph(
        "This report is generated automatically by the Loan Approval Prediction System "
        "for informational purposes only and does not constitute a final lending decision.",
        footer_style
    ))

    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
